# Generated by Django 6.1.1 on 2026-10-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], default='Dog', max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=1, help_text='Age in years')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('location', models.CharField(default='Dhaka', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the pet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_vaccinated', models.BooleanField(default=True, help_text='Up to date on vaccinations')),
                ('is_neutered', models.BooleanField(default=True, help_text='Spayed or neutered')),
                ('is_microchipped', models.BooleanField(default=True, help_text='Microchipped for identification')),
                ('good_with_kids', models.BooleanField(default=True, help_text='Safe and friendly with children')),
                ('good_with_pets', models.BooleanField(default=True, help_text='Sociable with other pets')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20)),
                ('energy_level', models.CharField(choices=[('Low', 'Low / Calm'), ('Moderate', 'Moderate'), ('High', 'High / Active')], default='Moderate', max_length=20)),
                ('rescue_story', models.TextField(blank=True, default='Lovingly rescued and rehabilitated at our shelter.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('reason', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('previous_pet_experience', models.BooleanField(default=False, help_text='Have you owned a pet before?')),
                ('message', models.TextField(blank=True, help_text='Additional notes or questions')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from shelter administrators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
